### ISSUE TITLE
Link for GitHub icon is wrong

### ISSUE THREAD

**Issue by serhatyuna** [scriptype/sorted-colors#1]
In [README file](https://github.com/scriptype/sorted-colors/blob/master/README.markdown), the link for GitHub icon is the same as the link of the arrow icon. Since I do not know the correct link, I did not create a pull request.

**Comment by scriptype** [comment]
Oh thanks for the heads-up, I should've broken it while editing that part, because it was correct in the beginning. I'll fix it soon.
